# Generated by Django 4.1.1 on 2022-09-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmswebapp', '0004_coviddata_alter_patient_birthdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CovidData',
        ),
    ]
