# Generated by Django 4.1.1 on 2022-09-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmswebapp', '0005_delete_coviddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='symptoms',
            new_name='appointmentfor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='prescription',
            new_name='details',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmenttime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
