# Generated by Django 4.1.1 on 2022-09-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmswebapp', '0006_rename_symptoms_appointment_appointmentfor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmenttime',
            field=models.CharField(max_length=50),
        ),
    ]
